name: Create a comment on new issues 

on: 
  issues:
    types: [opend]

    jobs:
    comment-with-action:
      runs-on: ubuntu-latest
      steps:
      - name: "dump github contect"
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash 
    

